### ISSUE TITLE
[version3] Segmentation fault in chain_state.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#727]
From mainnet1.libbitcoin.net.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000005cfd3d in libbitcoin::chain::chain_state::to_pool (top=..., version=<optimized out>) at src/chain/chain_state.cpp:474
474         return data;
(gdb) where
#0  0x00000000005cfd3d in libbitcoin::chain::chain_state::to_pool (top=..., version=<optimized out>) at src/chain/chain_state.cpp:474
#1  0x00000000005d215d in libbitcoin::chain::header::operator= (this=0x0, other=...) at src/chain/header.cpp:128
#2  0x0000000000000000 in ?? ()
```
Restarted after with good store because of write flushing.

**Comment by evoskuil** [comment]
Moving to blockchain.
